name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]  # every day at midnight UTC
  workflow_dispatch:                # allow manual runs

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: c1h1r1i1s1/metrics@master
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          user: c1h1r1i1s1
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Sydney

          # Plugins (choose what you want!)
          plugin_lines: yes
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_repositories: 100
          plugin_stars: yes
          plugin_topics: yes
          plugin_followup: yes
          plugin_notable: yes
