name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]  # every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: c1h1r1i1s1
          filename: github-metrics.svg

          # Base sections
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Sydney

          # Plugins
          plugin_lines: yes
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_stars: yes
